### PR TITLE
update all last commit 

### PR DESCRIPTION
**Pull request by ddkwork**

### CODE REVIEW

**Comment by ddkwork** [comment]
This PR mainly uses the goki module directly, and no longer uses the old module

**Review by kkoreilly — CHANGES_REQUESTED** [review]
Please remove the `pull.cmd` file and gitignore line. Other than that, this looks good.

**Comment by ddkwork** [comment]
> Please remove the `pull.cmd` file and gitignore line. Other than that, this looks good.

i will try

**Review by kkoreilly — APPROVED** [review]
Thanks!

**Pull request merged**
